language: ruby
bundler_args: --without development --deployment --jobs=3 --retry=3
cache: bundler
rvm:
#  - 1.9.3
  - 2.1.4
#  - 2.2.1
env:
  global:
    - MONSOON_OPENSTACK_AUTH_API_ENDPOINT=http://localhost:5000/v3
    - MONSOON_OPENSTACK_AUTH_API_USERID=admin
    - MONSOON_OPENSTACK_AUTH_API_PASSWORD=secret
    - HTTP_PROXY=http://proxy.wdf.sap.corp:8080
    - HTTP_PROXY=http://proxy.wdf.sap.corp:8080
    - HTTPS_PROXY=http://proxy.wdf.sap.corp:8080
    - NO_PROXY=.sap.corp,localhost
script:
  - bundle exec rspec
branches:
  only:
    #- master
    - authorization
notifications:
  email:
    on_success: [always] # default: change
    on_failure: [always] # default: always
  irc:
    channels:
      - "irc.sap.corp:6667#monsoon"
    on_success: [always] # default: always
    on_failure: [always] # default: always
